---
# Copyright 2019-present Open Networking Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

namespace: epc
nginx_hostname: "nginx"
cdn_node_selector: "node3"
spgwu_sgiip: 13.0.0.83
ue_ip_subnet1: 16.0.0.0/8
ue_ip_subnet2: 17.0.0.0/8

nginx:
  images:
    nginx_image: "woojoong/nginx:onf-video-v3"
  ports:
    rtmp_orig: 1935
    rtmp_np: 31935
    stream_orig: 1980
    stream_np: 31980
  replicas: 1

local_streaming:
  video_quality: 360
  nginx_ip: 127.0.0.1
  images:
    local_streaming_image: "woojoong/mwc-cdn:local-free-v2"
  ports:
    vlc: 8189
    vlc_np: 31989
    http: 50002
    http_np: 30502
  replicas: 2
  resources:
    cpu: 3
    mem: "1Gi"
