---
# Copyright 2018-present Open Networking Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Default values for ONOS
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

images:
  onos:
    repository: 'onosproject/onos'
    tag: '{{ .Chart.AppVersion }}'
    pullPolicy: 'Always'

global:
  registry: ''

kafka_logging:
  enabled: False
  brokers: ['cord-kafka:9092']

nameOverride: ''
fullnameOverride: ''

xos_service_label: ONOS

serviceAccountName: default

services:
  openflow:
    type: NodePort
    port: 6653
    nodePort: 31653
  ssh:
    type: NodePort
    port: 8101
    nodePort: 30115
  ui:
    type: NodePort
    port: 8181
    nodePort: 30120
  debugger:
    type: NodePort
    port: 5005
    nodePort: 30555
  ovsdb:
    type: ClusterIP
    port: 6640
  # Add application specific ports
  #progran:
  #  type: NodePort
  #  port: 4010
  #  nodePort: 30410

onos_env:
- name: POD_IP
  valueFrom:
  fieldRef:
    fieldPath: status.podIP
- name: NAMESPACE
  valueFrom:
  fieldRef:
    fieldPath: metadata.namespace
- name: ONOS_APPS
  value: "drivers,openflow-base"
- name: JAVA_DEBUG_PORT
  value: "0.0.0.0:5005"

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

application_logs: ''
