---
# Copyright 2017-present Open Networking Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: ConfigMap
metadata:
  name: gui-app-config
  labels:
    {{- include "xos-gui.release_labels" . | indent 4 }}
data:
  config: |
{{ include "xos-gui.app_config" . | indent 4 }}

...
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: gui-style-config
  labels:
    {{- include "xos-gui.release_labels" . | indent 4 }}
data:
  config: |
{{ include "xos-gui.style_config" . | indent 4 }}

...
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: gui-cord-version
  labels:
    {{- include "xos-gui.release_labels" . | indent 4 }}
data:
  config: |
{{ include "xos-gui.cord_version" . | indent 4 }}

