---
# Copyright 2017-present Open Networking Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Service
metadata:
  name: "xos-core"
  labels:
    {{- include "xos-core.release_labels" . | indent 4 }}
spec:
  type: NodePort
  selector:
    app: "xos-core"
  ports:
    - port: 50051
      targetPort: 50051
      name: secure
      nodePort: {{ .Values.xos_core_gRPCSecureNodePort }}
      protocol: TCP
    - port: 50055
      targetPort: 50055
      name: insecure
      nodePort: {{ .Values.xos_core_gRPCInsecureNodePort }}
      protocol: TCP

