---
# Copyright 2018-present Open Networking Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- if .Values.prometheus.enabled }}

apiVersion: v1
kind: ReplicationController
metadata:
  name: prometheus-cdn-rc
spec:
  replicas: 1
  selector:
    app: prometheus-cdn
  template:
    metadata:
      name: prometheus-cdn
      labels:
        app: prometheus-cdn
    spec:
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.prometheus.node_selector }}
      containers:
        - args:
            - --config.file=/etc/prometheus/config_out/prometheus.yml
          name: prometheus
          image: {{ .Values.prometheus.image  }}
          ports:
            - containerPort: 9090
          volumeMounts:
            - mountPath: /etc/prometheus/config_out
              name: prometheus-volume
      volumes:
        - name: prometheus-volume
          configMap:
            name: prometheus-config

{{- end }}