---
# Copyright 2018-present Open Networking Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

global:
  registry: ''

images:
  device_management:
    repository: 'opencord/device-management'
    tag: 'master'
    pullPolicy: 'Always'

device_management_grpcPort: 31085
device_management_httpPort: 30180
device_management_replicas: 1
device_management_pv_mount: '/tmp'

event_destip: ''

# persistence related vars
needPersistence: true
useCeph: true
pvClaimName: device-management-pv-claim
storageLDClassName: local-directory
storageCephClassName: cord-ceph-rbd
